name: fedora:37

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: fedora:37
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
      - name: Pull changes â¬‡ï¸
        uses: actions/checkout@v3

      - name: Install dependencies â¬‡ï¸
        run: |
          dnf install -y git python3-pyyaml

      - name: Build io.elementary.desktop ğŸ”¨
        run: |
          ./builder \
            --distro fedora:37 \
            --package-manager dnf \
            --recipes ./recipes \
            --package io.elementary.desktop
