name: ubuntu:22.04

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
      - name: Pull changes â¬‡ï¸
        uses: actions/checkout@v3

      - name: Install dependencies â¬‡ï¸
        run: |
          apt-get update
          apt-get install -y git python3-yaml

      - name: Build io.elementary.desktop ğŸ”¨
        run: |
          ./builder \
            --distro ubuntu:22.04 \
            --package io.elementary.desktop
